"""add_thumbnail_template_id

Revision ID: bf665d623b0b
Revises: 84d401b0e49d
Create Date: 2026-03-27 02:43:14.955644

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf665d623b0b"
down_revision: Union[str, None] = "84d401b0e49d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "thumbnails", sa.Column("template_id", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("thumbnails", "template_id")
    # ### end Alembic commands ###
